In [ ]:
# Import NumPy using the common alias np.
import numpy as np

In [ ]:
# Create a basic Python list that will be converted to a NumPy array.
list1 = [1,2,3,4,5]

In [ ]:
# Convert the Python list into a NumPy array.
arr_list1 = np.array(list1)

In [ ]:
# Check the data type to confirm it is a NumPy ndarray.
print(type(arr_list1))

<class 'numpy.ndarray'>


In [ ]:
# Combine two lists to build a 2D NumPy array.
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
arr_list1_2 =  np.array([list1,list2])
print((arr_list1_2))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Type check for a regular Python list with mixed int and float values.
a = [1,2,3.4,5,5]
print(type(a))

<class 'list'>


In [ ]:
# Stack three lists to create a 3x5 2D array.
list1 = [1,23,4,55,6]
list2 = [6,7,8,9,10]
list3 = [6,34,6,76,34]
arr_list1_3 = np.array([list1,list2,list3])
print (arr_list1_3)

[[ 1 23  4 55  6]
 [ 6  7  8  9 10]
 [ 6 34  6 76 34]]


In [ ]:
# ndim returns the number of dimensions (expected 2 here).
print(arr_list1_3.ndim)

2


In [ ]:
# NumPy array attributes: shape, size, dtype, ndim, min, max

In [ ]:
# Initialize a 2D array from a nested list.
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Print common array attributes and quick statistics.
print("shape",arr1.shape)
print("size",arr1.size)
print("min",arr1.min())
print("max",arr1.max())
print("dtype",arr1.dtype)
print("n_dim",arr1.ndim)


shape (2, 3)
size 6
min 1
max 6
dtype int64
n_dim 2


In [ ]:
# HW: Create 1D and 3D arrays, then check shape, size, dtype, and ndim.

In [ ]:
# Array initialization methods: zeros, ones, full, eye, empty, arange, linspace, random

In [ ]:
# zeros() creates an array of the given shape filled with 0s.
zero_arr = np.zeros((4,9))
print(zero_arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# ones() creates an array of the given shape filled with 1s.
one_arr = np.ones((4,9))
print(one_arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# full() initializes an array with a custom constant value.
full_arr = np.full((3,9),7)
print(full_arr)

[[7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7]]


In [ ]:
# eye() returns an identity matrix (1s on diagonal, 0s elsewhere).
id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# empty() allocates memory but values may be uninitialized/garbage.
print(np.empty (2))



[0. 0.]


In [ ]:
# arange(start, stop, step) creates evenly spaced discrete values.
print(np.arange(2,21,2))


[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
# linspace() returns a fixed number of values within a range.
print (np.linspace(1,10,4))



[ 1.  4.  7. 10.]


In [ ]:
# rand() generates random float values in [0, 1).
r_arr = np.random.rand(3,2)
print(r_arr)

[[0.02791706 0.68160632]
 [0.14386761 0.51760677]
 [0.03367346 0.23313424]]


In [ ]:
# randint(low, high, shape) generates random integers.
r_arr = np.random.randint(1,7,(5,5))
print(r_arr)

[[5 4 3 3 6]
 [2 1 4 2 3]
 [4 4 4 4 5]
 [1 4 6 6 3]
 [6 5 3 6 6]]


In [ ]:
# 1D array indexing and slicing examples.
a = np.array([1,2,4,5,5,6])
print(a)

[1 2 4 5 5 6]


In [ ]:
# Access a single element and a basic slice.
print(a[4])
print(a[0: 2])

5
[1 2]


In [ ]:
# ':' means full range, so this prints the entire array from index 0.
print(a[0: ])

# Slicing syntax: array[start:stop:step]
# Note: stop index is excluded from the output.
# Step controls how many indices are skipped.

[1 2 4 5 5 6]


In [ ]:
# Select the first three elements (indices 0, 1, 2).
print (a[0:3])

[1 2 4]


In [ ]:
# A large step selects sparse indices.
print(a[0:3:5])

[1]


In [ ]:
# 2D array structure: rows containing columns.
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10], ])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# arr2[1][0] -> first element of the second row.
print(arr2[1][0])

6


In [ ]:
# ':' selects all rows, and 0 selects the first column.
print(arr2[:, 0])

# 2D indexing format: [rows, columns]
# 3D indexing format: [depth/layer, rows, columns]


[1 6]


In [ ]:
# Multi-row 2D array for advanced indexing examples.
arr3 = np.array([
                  [1,2,3,4,5],
                  [6,7,8,9,10],
                  [32,34,34,56,76] ,
                  [45,67,43,35,45]
                  ])
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [32 34 34 56 76]
 [45 67 43 35 45]]


In [ ]:
# Third element (index 2) of the second row (index 1).
print(arr3[1][2])

8


In [ ]:
# Slice column index 1 for all rows (kept as 2D output).
print(arr3[::,1:2])

[[ 2]
 [ 7]
 [34]
 [67]]


In [ ]:
# The same slicing idea applies across both rows and columns.
print(arr3[::,1:2])

[[ 2]
 [ 7]
 [34]
 [67]]


In [ ]:
# Stacking combines smaller arrays into a larger array.
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))  # Vertical stack: combine by rows
print(np.hstack((a,b)))  # Horizontal stack: combine in sequence



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# Split operations are used to divide an array into parts.
# Example: np.hsplit(array, sections) or np.vsplit(array, sections)
# print(np.hsplit(sample_arr, 2))

In [ ]:
# Sample 1D array for arithmetic demonstrations.
a = np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]


In [ ]:
# Scalar operations apply the same number to every element.
print(a+10)
print(a-0)
print(a*10)
print(a/2)

[ 20  30  50 -20]
[ 10  20  40 -30]
[ 100  200  400 -300]
[  5.  10.  20. -15.]


In [ ]:
# Another array for element-wise function practice.
b = np.array([1,4,9])
print (b)

[1 4 9]


In [ ]:
# HW: Apply np.sin(), np.cos(), and np.tan() on array b.

In [ ]:
# Placeholder cell: add trigonometry homework code here.

In [ ]:
# Two equal-length vectors for element-wise operations.
a = np.array([1,2,3])
b = np.array ([4,5,6])
print (a)
print (b)

[1 2 3]
[4 5 6]


In [ ]:
# Built-in NumPy arithmetic functions (element-wise).
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# Dot product returns a single scalar for two vectors.
print(np.dot(a,b))

32


In [ ]:
# For a 1D array, transpose does not visibly change orientation.
print (a.T)

[1 2 3]


In [ ]:
# Create a 2D matrix to demonstrate transpose behavior.
t = np. array([[1,2,3,4,5],
               [6,7,8,9,10]])
print (t)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# In a 2D transpose, rows and columns are swapped.
print (t.T)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [ ]:
# Sample 2D array for statistical functions.
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# sum() returns the total of all elements in the array.
print(np.sum(a))

55


In [ ]:
# Common aggregate metrics: mean, sum, median, and standard deviation.
print(np.mean(a))
print(np.sum(a))
print(np.median(a))
print(np.std(a))


5.5
55
5.5
2.8722813232690143


In [ ]:
# End of the NumPy practice notebook.